export default [
  {
    id: 1,
    title: "Pig_Out",
    pigOne: "Sider",
    pigTwo: "Sider Dot",
    imageOne: "sider.png",
    imageTwo: "sider_dot.png",
    value: 0,
  },
  {
    id: 2,
    title: "Pig_Out",
    pigOne: "Sider Dot",
    pigTwo: "Sider",
    imageOne: "sider_dot.png",
    imageTwo: "sider.png",
    value: 0,
  },
  {
    id: 3,
    title: "Sider",
    pigOne: "Sider",
    pigTwo: "Sider",
    imageOne: "sider.png",
    imageTwo: "sider.png",
    value: 1,
  },
  {
    id: 4,
    title: "Sider",
    pigOne: "Sider Dot",
    pigTwo: "Sider Dot",
    imageOne: "sider_dot.png",
    imageTwo: "sider_dot.png",
    value: 1,
  },
  {
    id: 5,
    title: "Double Trotter",
    pigOne: "Trotter",
    pigTwo: "Trotter",
    imageOne: "trotter.png",
    imageTwo: "trotter.png",
    value: 20,
  },
  {
    id: 6,
    title: "Double Razorback",
    pigOne: "Razorback",
    pigTwo: "Razorback",
    imageOne: "razorback.png",
    imageTwo: "razorback.png",
    value: 20,
  },
  {
    id: 7,
    title: "Double Snouter",
    pigOne: "Snouter",
    pigTwo: "Snouter",
    imageOne: "snouter.png",
    imageTwo: "snouter.png",
    value: 40,
  },
  {
    id: 8,
    title: "Double Leaning Jowler",
    pigOne: "Leaning Jowler",
    pigTwo: "leaning Jowler",
    imageOne: "leaning_jowler.png",
    imageTwo: "leaning_jowler.png",
    value: 60,
  },
  {
    id: 9,
    title: "Mixed Combo",
    pigOne: "Trotter",
    pigTwo: "Sider",
    imageOne: "trotter.png",
    imageTwo: "sider.png",
    value: 5,
  },
  {
    id: 10,
    title: "Mixed Combo",
    pigOne: "Trotter",
    pigTwo: "Sider Dot",
    imageOne: "trotter.png",
    imageTwo: "sider_dot.png",
    value: 5,
  },
  {
    id: 11,
    title: "Mixed Combo",
    pigOne: "Trotter",
    pigTwo: "Razorback",
    imageOne: "trotter.png",
    imageTwo: "razorback.png",
    value: 10,
  },
  {
    id: 12,
    title: "Mixed Combo",
    pigOne: "Trotter",
    pigTwo: "Snouter",
    imageOne: "trotter.png",
    imageTwo: "snouter.png",
    value: 15,
  },
  {
    id: 13,
    title: "Mixed Combo",
    pigOne: "Trotter",
    pigTwo: "Leaning Jowler",
    imageOne: "trotter.png",
    imageTwo: "leaning_jowler.png",
    value: 20,
  },
  {
    id: 14,
    title: "Mixed Combo",
    pigOne: "Sider",
    pigTwo: "Trotter",
    imageOne: "sider.png",
    imageTwo: "trotter.png",
    value: 5,
  },
  {
    id: 15,
    title: "Mixed Combo",
    pigOne: "Sider Dot",
    pigTwo: "Trotter",
    imageOne: "sider_dot.png",
    imageTwo: "trotter.png",
    value: 5,
  },
  {
    id: 16,
    title: "Mixed Combo",
    pigOne: "Razorback",
    pigTwo: "Trotter",
    imageOne: "razorback.png",
    imageTwo: "trotter.png",
    value: 10,
  },
  {
    id: 17,
    title: "Mixed Combo",
    pigOne: "Snouter",
    pigTwo: "Trotter",
    imageOne: "snouter.png",
    imageTwo: "trotter.png",
    value: 15,
  },
  {
    id: 18,
    title: "Mixed Combo",
    pigOne: "Leaning Jowler",
    pigTwo: "Trotter",
    imageOne: "leaning_jowler.png",
    imageTwo: "trotter.png",
    value: 20,
  },
  {
    id: 19,
    title: "Mixed Combo",
    pigOne: "Razorback",
    pigTwo: "Sider",
    imageOne: "razorback.png",
    imageTwo: "sider.png",
    value: 5,
  },
  {
    id: 20,
    title: "Mixed Combo",
    pigOne: "Razorback",
    pigTwo: "Sider Dot",
    imageOne: "razorback.png",
    imageTwo: "sider_dot.png",
    value: 5,
  },
  {
    id: 21,
    title: "Mixed Combo",
    pigOne: "Razorback",
    pigTwo: "Snouter",
    imageOne: "razorback.png",
    imageTwo: "snouter.png",
    value: 15,
  },
  {
    id: 22,
    title: "Mixed Combo",
    pigOne: "Razorback",
    pigTwo: "Leaning Jowler",
    imageOne: "razorback.png",
    imageTwo: "leaning_jowler.png",
    value: 20,
  },
  {
    id: 23,
    title: "Mixed Combo",
    pigOne: "Sider",
    pigTwo: "Razorback",
    imageOne: "sider.png",
    imageTwo: "razorback.png",
    value: 5,
  },
  {
    id: 24,
    title: "Mixed Combo",
    pigOne: "Sider Dot",
    pigTwo: "Razorback",
    imageOne: "sider_dot.png",
    imageTwo: "razorback.png",
    value: 5,
  },
  {
    id: 25,
    title: "Mixed Combo",
    pigOne: "Snouter",
    pigTwo: "Razorback",
    imageOne: "snouter.png",
    imageTwo: "razorback.png",
    value: 15,
  },
  {
    id: 26,
    title: "Mixed Combo",
    pigOne: "Leaning Jowler",
    pigTwo: "Razorback",
    imageOne: "leaning_jowler.png",
    imageTwo: "razorback.png",
    value: 20,
  },
  {
    id: 27,
    title: "Mixed Combo",
    pigOne: "Snouter",
    pigTwo: "Sider",
    imageOne: "snouter.png",
    imageTwo: "sider.png",
    value: 10,
  },
  {
    id: 28,
    title: "Mixed Combo",
    pigOne: "Snouter",
    pigTwo: "Sider Dot",
    imageOne: "snouter.png",
    imageTwo: "sider_dot.png",
    value: 10,
  },
  {
    id: 29,
    title: "Mixed Combo",
    pigOne: "Snouter",
    pigTwo: "Leaning Jowler",
    imageOne: "snouter.png",
    imageTwo: "leaning_jowler.png",
    value: 25,
  },
  {
    id: 30,
    title: "Mixed Combo",
    pigOne: "Sider",
    pigTwo: "Snouter",
    imageOne: "sider.png",
    imageTwo: "snouter.png",
    value: 10,
  },
  {
    id: 31,
    title: "Mixed Combo",
    pigOne: "Sider Dot",
    pigTwo: "Snouter",
    imageOne: "sider_dot.png",
    imageTwo: "snouter.png",
    value: 10,
  },
  {
    id: 32,
    title: "Mixed Combo",
    pigOne: "Leaning Jowler",
    pigTwo: "Snouter",
    imageOne: "leaning_jowler.png",
    imageTwo: "snouter.png",
    value: 25,
  },
  {
    id: 33,
    title: "Mixed Combo",
    pigOne: "Leaning Jowler",
    pigTwo: "Sider",
    imageOne: "leaning_jowler.png",
    imageTwo: "sider.png",
    value: 15,
  },
  {
    id: 34,
    title: "Mixed Combo",
    pigOne: "Leaning Jowler",
    pigTwo: "Sider Dot",
    imageOne: "leaning_jowler.png",
    imageTwo: "sider_dot.png",
    value: 15,
  },
  {
    id: 35,
    title: "Mixed Combo",
    pigOne: "Sider",
    pigTwo: "Leaning Jowler",
    imageOne: "sider.png",
    imageTwo: "leaning_jowler.png",
    value: 15,
  },
  {
    id: 36,
    title: "Mixed Combo",
    pigOne: "Sider Dot",
    pigTwo: "Leaning Jowler",
    imageOne: "sider_dot.png",
    imageTwo: "leaning_jowler.png",
    value: 15,
  },
  {
    id: 37,
    title: "Oinker",
    pigOne: "Oinker",
    pigTwo: "Oiner",
    imageOne: "oinker.png",
    imageTwo: "oinker.png",
    value: 0,
  },
];
