import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState, useEffect } from "react";
import { GameContext } from "../context/context";

export default function Home() {
  const [highScore, setHighScore] = useState(0);

  useEffect(() => {
    setHighScore(parseInt(localStorage.getItem("passThePigs")));
  }, []);

  return (
    <GameContext.Provider value={{ highScore, setHighScore }}>
      <div className={styles.container}>
        <Head>
          <title>Pass the Pigs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Image
            priority
            src="/images/pass_the_pigs_title.png"
            height={500}
            width={500}
            alt="Pass the pigs title"
          />
          <p className={styles.description}>
            <Link href="/game">PLAY</Link>
          </p>
          <p className={styles.description}>
            <Link href="/rules">RULES</Link>
          </p>
          <p className={styles.description}>High Score: {highScore}</p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </GameContext.Provider>
  );
}
